name: build and publish deb

on:
  workflow_dispatch:
    inputs:
      manual_trigger:
        description: 'Manually trigger the workflow'
        required: true

jobs:
  build_testing:
    runs-on: ubuntu-22.04
    steps:
      - uses: jspricke/ros-deb-builder-action@main
        with:
          ROS_DISTRO: humble
          DEB_DISTRO: jammy
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}